// Andhra Pradesh Districts and Mandals Data (Latest as of 2024)
// Source: Official Andhra Pradesh Government data

export interface DistrictMandal {
  district: string;
  mandals: string[];
}

export const andhraPradeshDistricts: DistrictMandal[] = [
  {
    district: 'Alluri Sitharama Raju',
    mandals: [
      'Addateegala',
      'Ananthagiri',
      'Araku Valley',
      'Chintapalle',
      'Chintur',
      'Devipatnam',
      'Dumbriguda',
      'Etapaka',
      'Gangavaram',
      'Gudem Kotha Veedhi',
      'Hukumpeta',
      'Koyyuru',
      'Kunavaram',
      'Maredumilli',
      'Munchingiputtu',
      'Nellipaka',
      'Paderu',
      'Peddabayalu',
      'Rajavommangi',
      'Rampachodavaram',
      'Vararamachandrapuram',
      'Y. Ramavaram',
    ],
  },
  {
    district: 'Anakapalli',
    mandals: [
      'Anakapalli',
      'Atchutapuram',
      'Bheemunipatnam',
      'Chodavaram',
      'Devarapalle',
      'Elamanchili',
      'Kasimkota',
      'Makavarapalem',
      'Munagapaka',
      'Nakkapalle',
      'Narsipatnam',
      'Pendurthi',
      'Ravikamatham',
      'Rolugunta',
      'Sabbavaram',
      'Yelamanchili',
    ],
  },
  {
    district: 'Anantapur',
    mandals: [
      'Anantapur',
      'Atmakur',
      'Bathalapalle',
      'Beluguppa',
      'Bommanahal',
      'Brahmasamudram',
      'Bukkarayasamudram',
      'Dharmavaram',
      'Garladinne',
      'Gooty',
      'Gudibanda',
      'Guntakal',
      'Hindupur',
      'Kadiri',
      'Kalyandurg',
      'Kanekal',
      'Kundurpi',
      'Lepakshi',
      'Madakasira',
      'Nallamada',
      'Narpala',
      'Pamidi',
      'Parigi',
      'Peddavadugur',
      'Penukonda',
      'Puttaparthi',
      'Raptadu',
      'Rayadurg',
      'Roddam',
      'Settur',
      'Singanamala',
      'Tadimarri',
      'Tadpatri',
      'Talupula',
      'Uravakonda',
      'Vajrakarur',
      'Vidapanakal',
      'Yadiki',
      'Yellanur',
    ],
  },
  {
    district: 'Annamayya',
    mandals: [
      'B.Kothakota',
      'Chinnamandem',
      'Chitvel',
      'Galiveedu',
      'Gurramkonda',
      'Kalakada',
      'Kalikiri',
      'Kambhamvaripalle',
      'Kodur',
      'Kurabalakota',
      'Lakkireddipalle',
      'Madanapalle',
      'Mulakalacheruvu',
      'Nandalur',
      'Nimmanapalle',
      'Obulavaripalle',
      'Penagaluru',
      'Pileru',
      'Pullampeta',
      'Railway Koduru',
      'Rajampet',
      'Ramapuram',
      'Rayachoti',
      'Sambepalle',
      'Sodam',
      'T.Sundupalle',
      'Thamballapalle',
      'Valmikipuram',
      'Vayalpad',
      'Veeraballe',
    ],
  },
  {
    district: 'Bapatla',
    mandals: [
      'Bapatla',
      'Cherukupalle',
      'Duggirala',
      'Karlapalem',
      'Kollur',
      'Nizampatnam',
      'Nutanakallu',
      'Parchur',
      'Repalle',
      'Sangam Jagarlamudi',
      'Tsundur',
      'Vemuru',
    ],
  },
  {
    district: 'Chittoor',
    mandals: [
      'B.Kothakota',
      'Chandragiri',
      'Chittoor',
      'Gangavaram',
      'Gudipala',
      'Gurramkonda',
      'Irala',
      'Kalakada',
      'Kalikiri',
      'Kuppam',
      'Madanapalle',
      'Mulakalacheruvu',
      'Nagari',
      'Narayanavanam',
      'Palasamudram',
      'Palamaner',
      'Peddapanjani',
      'Penumuru',
      'Pileru',
      'Punganur',
      'Puthalapattu',
      'Ramakuppam',
      'Rompicherla',
      'Santhipuram',
      'Sodam',
      'Srikalahasti',
      'Thamballapalle',
      'Thottambedu',
      'Tirupati (Rural)',
      'Tirupati (Urban)',
      'Vadamalapeta',
      'Varadaiahpalem',
      'Vayalpad',
      'Vedurukuppam',
      'Venkatagiri',
      'Yerpedu',
      'Yerravaripalem',
    ],
  },
  {
    district: 'East Godavari',
    mandals: [
      'Anaparthi',
      'Biccavolu',
      'Chagallu',
      'Devarapalle',
      'Gokavaram',
      'Gopalapuram',
      'Kadiam',
      'Korukonda',
      'Kovvur',
      'Nallajerla',
      'Nidadavole',
      'Peravali',
      'Rajahmundry (Rural)',
      'Rajahmundry (Urban)',
      'Rajanagaram',
      'Rangampeta',
      'Seethanagaram',
      'Thallapudi',
      'Undrajavaram',
    ],
  },
  {
    district: 'Eluru',
    mandals: [
      'Achanta',
      'Akividu',
      'Attili',
      'Bhimadole',
      'Buttayagudem',
      'Chintalapudi',
      'Denduluru',
      'Dwaraka Tirumala',
      'Eluru',
      'Ganapavaram',
      'Iragavaram',
      'Jangareddygudem',
      'Kamavarapukota',
      'Kovvur',
      'Lingapalem',
      'Nallajerla',
      'Nidamarru',
      'Nuzvid',
      'Pedapadu',
      'Pedavegi',
      'Polavaram',
      'Tadepalligudem',
      'Thallapudi',
      'Undi',
      'Unguturu',
      'Veeravasaram',
    ],
  },
  {
    district: 'Guntur',
    mandals: [
      'Amaravati',
      'Bapatla',
      'Bollapalle',
      'Chebrolu',
      'Dachepalle',
      'Duggirala',
      'Guntur',
      'Kakumanu',
      'Kollipara',
      'Kollur',
      'Macherla',
      'Mangalagiri',
      'Nadendla',
      'Narasaraopet',
      'Nekarikallu',
      'Parchur',
      'Pedakakani',
      'Pedanandipadu',
      'Phirangipuram',
      'Piduguralla',
      'Prathipadu',
      'Rentachintala',
      'Repalle',
      'Sattenapalle',
      'Tadikonda',
      'Tenali',
      'Thullur',
      'Tsundur',
      'Vatticherukuru',
      'Vemuru',
      'Vinukonda',
    ],
  },
  {
    district: 'Kadapa',
    mandals: [
      'Badvel',
      'B.Kodur',
      'Chakrayapet',
      'Chinnamandem',
      'Chitvel',
      'Duvvur',
      'Galiveedu',
      'Jammalamadugu',
      'Kadapa',
      'Kamalapuram',
      'Khajipet',
      'Kondapuram',
      'Lakkireddipalle',
      'Muddanur',
      'Mydukur',
      'Nandalur',
      'Obulavaripalle',
      'Pendlimarri',
      'Porumamilla',
      'Pulivendula',
      'Rajampet',
      'Rajupalem',
      'Rayachoti',
      'Siddavattam',
      'T Sundupalle',
      'Vallur',
      'Veeraballe',
      'Vempalle',
      'Yerraguntla',
    ],
  },
  {
    district: 'Kakinada',
    mandals: [
      'Allavaram',
      'Amalapuram',
      'Atreyapuram',
      'Chintalapudi',
      'Gollaprolu',
      'I.Polavaram',
      'Kakinada (Rural)',
      'Kakinada (Urban)',
      'Kapileswarapuram',
      'Karapa',
      'Katrenikona',
      'Kothapeta',
      'Malikipuram',
      'Mandapeta',
      'Mummidivaram',
      'P.Gannavaram',
      'Peddapuram',
      'Rajanagaram',
      'Rampachodavaram',
      'Ravulapalem',
      'Rayavaram',
      'Sakhinetipalle',
      'Samalkota',
      'Thallarevu',
      'Thondangi',
      'Uppalaguptam',
      'Yeleswaram',
    ],
  },
  {
    district: 'Konaseema',
    mandals: [
      'Allavaram',
      'Amalapuram',
      'Atreyapuram',
      'I.Polavaram',
      'Kapileswarapuram',
      'Katrenikona',
      'Kothapeta',
      'Malikipuram',
      'Mummidivaram',
      'P.Gannavaram',
      'Rampachodavaram',
      'Ravulapalem',
      'Rayavaram',
      'Sakhinetipalle',
      'Thallarevu',
      'Uppalaguptam',
    ],
  },
  {
    district: 'Krishna',
    mandals: [
      'Avanigadda',
      'Bantumilli',
      'Bapulapadu',
      'Challapalli',
      'Chandarlapadu',
      'G.Konduru',
      'Gampalagudem',
      'Gannavaram',
      'Ghantasala',
      'Gudivada',
      'Gudlavalleru',
      'Ibrahimpatnam',
      'Jaggayyapeta',
      'Kankipadu',
      'Kanuru',
      'Koduru',
      'Kruthivennu',
      'Machilipatnam',
      'Mopidevi',
      'Movva',
      'Mudinepalle',
      'Nandigama',
      'Nandivada',
      'Nuzvid',
      'Pamarru',
      'Pedana',
      'Penuganchiprolu',
      'Penugolanu',
      'Reddigudem',
      'Thotlavalluru',
      'Tiruvuru',
      'Unguturu',
      'Vatsavai',
      'Veerullapadu',
      'Vijayawada (Rural)',
      'Vijayawada (Urban)',
      'Vuyyuru',
    ],
  },
  {
    district: 'Kurnool',
    mandals: [
      'Adoni',
      'Alur',
      'Aspari',
      'Atmakur',
      'Banaganapalle',
      'Bandi Atmakur',
      'C.Belagal',
      'Chagalamarri',
      'Chippagiri',
      'Devanakonda',
      'Dhone',
      'Gonegandla',
      'Gudur',
      'Halaharvi',
      'Holagunda',
      'Jupadu Bungalow',
      'Kallur',
      'Kodumur',
      'Koilkuntla',
      'Kolimigundla',
      'Kosigi',
      'Kothapalle',
      'Kowthalam',
      'Kurnool',
      'Maddikera',
      'Mahanandi',
      'Mantralayam',
      'Nandavaram',
      'Nandyal',
      'Orvakal',
      'Pagidyala',
      'Pamulapadu',
      'Panyam',
      'Pattikonda',
      'Peapally',
      'Pedda Kadubur',
      'Rudravaram',
      'Sanjamala',
      'Sirvel',
      'Srisailam',
      'Tuggali',
      'Uyyalawada',
      'Veldurthi',
      'Velgode',
      'Yemmiganur',
    ],
  },
  {
    district: 'Nandyal',
    mandals: [
      'Allagadda',
      'Atmakur',
      'Banaganapalle',
      'Bethamcherla',
      'Dhone',
      'Gospadu',
      'Jupadu Bungalow',
      'Kallur',
      'Koilkuntla',
      'Kolimigundla',
      'Kothapalle',
      'Mahanandi',
      'Nandikotkur',
      'Nandyal',
      'Orvakal',
      'Pamulapadu',
      'Panyam',
      'Rudravaram',
      'Sanjamala',
      'Sirvel',
      'Uyyalawada',
      'Velgode',
    ],
  },
  {
    district: 'NTR',
    mandals: [
      'Avanigadda',
      'Bapulapadu',
      'Chandarlapadu',
      'G.Konduru',
      'Gannavaram',
      'Ibrahimpatnam',
      'Jaggayyapeta',
      'Kanuru',
      'Kankipadu',
      'Mylavaram',
      'Nandigama',
      'Penuganchiprolu',
      'Penugolanu',
      'Reddigudem',
      'Thotlavalluru',
      'Tiruvuru',
      'Vatsavai',
      'Veerullapadu',
      'Vijayawada (Rural)',
      'Vijayawada (Urban)',
    ],
  },
  {
    district: 'Palnadu',
    mandals: [
      'Bollapalle',
      'Dachepalle',
      'Duggirala',
      'Gurazala',
      'Kakumanu',
      'Karempudi',
      'Macharla',
      'Macherla',
      'Nadendla',
      'Narasaraopet',
      'Nekarikallu',
      'Piduguralla',
      'Rentachintala',
      'Sattenapalle',
      'Vinukonda',
    ],
  },
  {
    district: 'Parvathipuram Manyam',
    mandals: [
      'Bondapalle',
      'Gajapathinagaram',
      'Gantyada',
      'Gummalakshmipuram',
      'Jiyyammavalasa',
      'Komarada',
      'Kurupam',
      'Makkuva',
      'Parvathipuram',
      'Peddabayalu',
      'Salur',
      'Seethampeta',
      'Veeraghattam',
    ],
  },
  {
    district: 'Prakasam',
    mandals: [
      'Addanki',
      'Ardhaveedu',
      'Ballikurava',
      'Bestavaripeta',
      'Chandrasekharapuram',
      'Chirala',
      'Cumbum',
      'Darsi',
      'Donakonda',
      'Giddalur',
      'Gudlur',
      'Hanumanthunipadu',
      'Inkollu',
      'Jarugumilli',
      'Kandukur',
      'Kanigiri',
      'Karamchedu',
      'Kondapi',
      'Korisapadu',
      'Kurichedu',
      'Lingasamudram',
      'Maddipadu',
      'Markapur',
      'Martur',
      'Mundlamuru',
      'Naguluppalapadu',
      'Ongole',
      'Pamur',
      'Parchur',
      'Pedacherlopalle',
      'Peddaraveedu',
      'Ponnalur',
      'Pullalacheruvu',
      'Racherla',
      'Santhamaguluru',
      'Santamaguluru',
      'Singarayakonda',
      'Tarlupadu',
      'Thallur',
      'Tripuranthakam',
      'Ulavapadu',
      'Veligandla',
      'Vetapalem',
      'Voletivaripalem',
      'Yerragondapalem',
      'Zarugumilli',
    ],
  },
  {
    district: 'SPSR Nellore',
    mandals: [
      'Allur',
      'Anamasamudram',
      'Ananthasagaram',
      'Atmakur',
      'Bogole',
      'Buchireddypalem',
      'Chejerla',
      'Chillakur',
      'Dagadarthi',
      'Dakkili',
      'Doravarisatram',
      'Duttalur',
      'Gudur',
      'Indukurpet',
      'Jaladanki',
      'Kaligiri',
      'Kaluvoya',
      'Kandukur',
      'Kavali',
      'Kodavalur',
      'Kondapuram',
      'Kota',
      'Kovur',
      'Manubolu',
      'Marripadu',
      'Muthukur',
      'Nellore (Rural)',
      'Nellore (Urban)',
      'Ozili',
      'Pellakur',
      'Podalakur',
      'Rapur',
      'Sangam',
      'Seetharamapuram',
      'Sydapuram',
      'Thotapalligudur',
      'Udayagiri',
      'Vakadu',
      'Varikuntapadu',
      'Venkatachalam',
      'Vidavalur',
      'Vinjamur',
    ],
  },
  {
    district: 'Srikakulam',
    mandals: [
      'Amadalavalasa',
      'Bhamini',
      'Burja',
      'Etcherla',
      'Gara',
      'Hiramandalam',
      'Ichchapuram',
      'Jalumuru',
      'Kanchili',
      'Kaviti',
      'Kotabommali',
      'Kothuru',
      'L.N.Peta',
      'Laveru',
      'Mandasa',
      'Nandigam',
      'Narasannapeta',
      'Palakonda',
      'Palasa',
      'Pathapatnam',
      'Polaki',
      'Ponduru',
      'Rajam',
      'Ranastalam',
      'Regidi Amadalavalasa',
      'Sanaba',
      'Sarubujjili',
      'Seethampeta',
      'Sompeta',
      'Tekkali',
      'Vajrapukothuru',
      'Veeraghattam',
    ],
  },
  {
    district: 'Sri Sathya Sai',
    mandals: [
      'Amadagur',
      'Bukkapatnam',
      'Chilamathur',
      'Gorantla',
      'Gudibanda',
      'Hindupur',
      'Kadiri',
      'Kothacheruvu',
      'Madakasira',
      'Nallacheruvu',
      'Nallamada',
      'Narpala',
      'O.D.Cheruvu',
      'Pamidi',
      'Parigi',
      'Penukonda',
      'Puttaparthi',
      'Roddam',
      'Rolla',
      'Settur',
      'Somandepalle',
      'Talupula',
      'Vidapanakal',
      'Yellanur',
    ],
  },
  {
    district: 'Tirupati',
    mandals: [
      'B.Kothakota',
      'Chandragiri',
      'Chinnagottigallu',
      'Gangavaram',
      'Gudipala',
      'Gurramkonda',
      'Irala',
      'Kalakada',
      'Kalikiri',
      'Kuppam',
      'Mulakalacheruvu',
      'Nagari',
      'Narayanavanam',
      'Palasamudram',
      'Palamaner',
      'Peddapanjani',
      'Penumuru',
      'Pileru',
      'Punganur',
      'Puthalapattu',
      'Ramakuppam',
      'Rompicherla',
      'Santhipuram',
      'Sodam',
      'Srikalahasti',
      'Thamballapalle',
      'Thottambedu',
      'Tirupati (Rural)',
      'Tirupati (Urban)',
      'Vadamalapeta',
      'Varadaiahpalem',
      'Vayalpad',
      'Vedurukuppam',
      'Yerpedu',
      'Yerravaripalem',
    ],
  },
  {
    district: 'Visakhapatnam',
    mandals: [
      'Anandapuram',
      'Anakapalli',
      'Araku Valley',
      'Atchutapuram',
      'Bheemunipatnam',
      'Butchayyapeta',
      'Cheedikada',
      'Chintapalle',
      'Chodavaram',
      'Devarapalle',
      'Dumbriguda',
      'Elamanchili',
      'Gajapathinagaram',
      'Gantyada',
      'Golugonda',
      'Gudem Kotha Veedhi',
      'Hukumpeta',
      'Kasimkota',
      'Kotavuratla',
      'Koyyuru',
      'Lakkavarapukota',
      'Makavarapalem',
      'Munagapaka',
      'Munchingiputtu',
      'Nakkapalle',
      'Narsipatnam',
      'Nathavaram',
      'Paderu',
      'Pendurthi',
      'Ravikamatham',
      'Rolugunta',
      'Sabbavaram',
      'S.Rayavaram',
      'Visakhapatnam (Rural)',
      'Visakhapatnam (Urban)',
      'Yelamanchili',
    ],
  },
  {
    district: 'Vizianagaram',
    mandals: [
      'Badangi',
      'Bhogapuram',
      'Bobbili',
      'Bondapalle',
      'Cheepurupalle',
      'Denkada',
      'Gajapathinagaram',
      'Gantyada',
      'Garugubilli',
      'Gummalakshmipuram',
      'Jami',
      'Jiyyammavalasa',
      'Komarada',
      'Kothavalasa',
      'Kurupam',
      'Lakkavarapukota',
      'Makkuva',
      'Merakamudidam',
      'Nellimarla',
      'Parvathipuram',
      'Peddabayalu',
      'Pusapatirega',
      'Rama',
      'Salur',
      'Seethampeta',
      'Srivilliputtur',
      'Therlam',
      'Vepada',
      'Vizianagaram',
    ],
  },
  {
    district: 'West Godavari',
    mandals: [
      'Achanta',
      'Akividu',
      'Attili',
      'Bhimadole',
      'Buttayagudem',
      'Chintalapudi',
      'Denduluru',
      'Dwaraka Tirumala',
      'Eluru',
      'Ganapavaram',
      'Iragavaram',
      'Jangareddygudem',
      'Kamavarapukota',
      'Kovvur',
      'Lingapalem',
      'Nallajerla',
      'Nidamarru',
      'Pedapadu',
      'Pedavegi',
      'Polavaram',
      'Tadepalligudem',
      'Thallapudi',
      'Undi',
      'Unguturu',
      'Veeravasaram',
    ],
  },
];

// Get all districts as a simple array
export const getAllDistricts = (): string[] => {
  return andhraPradeshDistricts.map((d) => d.district).sort();
};

// Get mandals for a specific district
export const getMandalsByDistrict = (district: string): string[] => {
  const districtData = andhraPradeshDistricts.find(
    (d) => d.district.toLowerCase() === district.toLowerCase()
  );
  return districtData ? districtData.mandals.sort() : [];
};

// Get all unique mandals across all districts
export const getAllMandals = (): string[] => {
  const allMandals = new Set<string>();
  andhraPradeshDistricts.forEach((district) => {
    district.mandals.forEach((mandal) => allMandals.add(mandal));
  });
  return Array.from(allMandals).sort();
};

