// Andhra Pradesh Districts and Mandals Data
// Source: Official Andhra Pradesh Government data (as provided)

export interface DistrictMandal {
  district: string;
  mandals: string[];
}

export const andhraPradeshDistricts: DistrictMandal[] = [
  {
    district: 'Alluri Sitharama Raju',
    mandals: [
      'Ananthagiri',
      'Araku Valley',
      'Chinthapalli',
      'Dumbriguda',
      'Ganagaraju Madugula',
      'Gudem Kotha Veedhi',
      'Hukumpeta',
      'Koyyuru',
      'Munchingiputtu',
      'Paderu',
      'Pedabayalu',
    ],
  },
  {
    district: 'Anakapalli',
    mandals: [
      'Anakapalli',
      'Atchutapuram',
      'Butchayyapeta',
      'Cheedikada',
      'Chodavaram',
      'Devarapalli',
      'Elamanchili',
      'Golugonda',
      'K. Kotapadu',
      'Kasimkota',
      'Kotauratla',
      'Madugula',
      'Makavarapalem',
      'Munagapaka',
      'Nakkapalle',
      'Narsipatnam',
      'Nathavaram',
      'Paravada',
      'Payakaraopeta',
      'Rambilli',
      'Ravikamatham',
      'Rolugunta',
      'S. Rayavaram',
      'Sabbavaram',
    ],
  },
  {
    district: 'Anantapur',
    mandals: [
      'Anantapuramu Rural',
      'Anantapuramu Urban',
      'Atmakur',
      'Beluguppa',
      'Bommanahal',
      'Brahmasamudram',
      'Bukkaraya Samudram',
      'D.Hirehal',
      'Garladinne',
      'Gooty',
      'Gummagatta',
      'Guntakal',
      'Kalyandurg',
      'Kambadur',
      'Kanekal',
      'Kudair',
      'Kundurpi',
      'Narpala',
      'Pamidi',
      'Peddapappur',
      'Peddavadugur',
      'Putlur',
      'Raptadu',
      'Rayadurgam',
      'Settur',
      'Singanamala',
      'Tadipatri',
      'Uravakonda',
      'Vajrakarur',
      'Vidapanakal',
      'Yadiki',
      'Yellanur',
    ],
  },
  {
    district: 'Annamayya',
    mandals: [
      'Beerangi Kothakota',
      'Chinnamandyam',
      'Chowdepalle',
      'Galiveedu',
      'Gurramkonda',
      'Kalakada',
      'Kalikiri',
      'Kambhamvaripalle',
      'Kurabalakota',
      'Lakkireddipalli',
      'Madanapalle',
      'Mulakalacheruvu',
      'Nimmanapalle',
      'Peddamandyam',
      'Peddathippasamudram',
      'Pileru',
      'Punganur',
      'Ramasamudram',
      'Ramapuram',
      'Rayachoti',
      'Sambepalli',
      'Sodam',
      'Somala',
      'Thamballapalle',
      'Vayalpad',
    ],
  },
  {
    district: 'Bapatla',
    mandals: [
      'Amruthalur',
      'Bapatla',
      'Bhattiprolu',
      'Cherukupalle',
      'Chinaganjam',
      'Chirala',
      'Inkollu',
      'Karlapalem',
      'Karamchedu',
      'Kollur',
      'Martur',
      'Nagaram',
      'Nizampatnam',
      'Parchur',
      'Pittalavanipalem',
      'Repalle',
      'Tsunduru',
      'Vetapalem',
      'Vemuru',
      'Yeddanapudi',
    ],
  },
  {
    district: 'Chittoor',
    mandals: [
      'Baireddipalle',
      'Bangarupalyam',
      'Chittoor Rural',
      'Chittoor Urban',
      'Gangadhara Nellore',
      'Gangavaram',
      'Gudipala',
      'Gudupalle',
      'Irala',
      'Karvetinagar',
      'Kuppam',
      'Nagari',
      'Nindra',
      'Palamaner',
      'Palasamudram',
      'Peddapanjani',
      'Penumuru',
      'Pulicherla',
      'Puthalapattu',
      'Ramakuppam',
      'Rompicherla',
      'Santhipuram',
      'Srirangarajapuram',
      'Thavanampalle',
      'Vadamalapeta',
      'Varadaiahpalem',
      'Vedurukuppam',
      'Venkatagirikota',
      'Vijayapuram',
      'Yadamari',
    ],
  },
  {
    district: 'East Godavari',
    mandals: [
      'Anaparthi',
      'Biccavolu',
      'Chagallu',
      'Devarapalle',
      'Gokavaram',
      'Gopalapuram',
      'Kadiam',
      'Korukonda',
      'Kovvur',
      'Nallajerla',
      'Nidadavolu',
      'Peravali',
      'Rajanagaram',
      'Rajamahendravaram Rural',
      'Rajamahendravaram Urban',
      'Rangampeta',
      'Seethanagaram',
      'Tallapudi',
      'Undrajavaram',
    ],
  },
  {
    district: 'Eluru',
    mandals: [
      'Agiripalli',
      'Achanta',
      'Akividu',
      'Attili',
      'Bhimadole',
      'Buttayagudem',
      'Chatrai',
      'Chintalapudi',
      'Denduluru',
      'Dwaraka Tirumala',
      'Eluru',
      'Ganapavaram',
      'Iragavaram',
      'Jangareddygudem',
      'Jeelugu Milli',
      'Kamavarapukota',
      'Kaikalur',
      'Kalidindi',
      'Koyyalagudem',
      'Kukunuru',
      'Kovvur',
      'Lingapalem',
      'Mandavalli',
      'Mudinepalli',
      'Musunuru',
      'Nallajerla',
      'Nidamarru',
      'Nuzvid',
      'Pedapadu',
      'Pedavegi',
      'Polavaram',
      'T. Narasapuram',
      'Tadepalligudem',
      'Thallapudi',
      'Undi',
      'Unguturu',
      'Veeravasaram',
      'Velairpadu',
    ],
  },
  {
    district: 'Guntur',
    mandals: [
      'Chebrolu',
      'Duggirala',
      'Guntur East',
      'Guntur West',
      'Kakumanu',
      'Kollipara',
      'Mangalagiri',
      'Medikonduru',
      'Pedakakani',
      'Pedanandipadu',
      'Phirangipuram',
      'Ponnur',
      'Prathipadu',
      'Tadepalle',
      'Tadikonda',
      'Tenali',
      'Thullur',
      'Vatticherukuru',
    ],
  },
  {
    district: 'Kakinada',
    mandals: [
      'Gandepalle',
      'Gollaprolu',
      'Jaggampeta',
      'Kajuluru',
      'Kakinada Rural',
      'Kakinada Urban',
      'Karapa',
      'Kirlampudi',
      'Kotananduru',
      'P. Gannavaram',
      'Peddapuram',
      'Pithapuram',
      'Prathipadu',
      'Rajanagaram',
      'Rampachodavaram',
      'Ravulapalem',
      'Rayavaram',
      'Rowthulapudi',
      'Sakhinetipalle',
      'Samalkota',
      'Sankhavaram',
      'Thallarevu',
      'Thondangi',
      'Tuni',
      'U. Kothapalli',
      'Uppalaguptam',
      'Yeleswaram',
    ],
  },
  {
    district: 'Konaseema',
    mandals: [
      'Ainavilli',
      'Allavaram',
      'Alumuru',
      'Ambajipeta',
      'Amalapuram',
      'Atreyapuram',
      'I. Polavaram',
      'K. Gangavaram mandal',
      'Kapileswarapuram',
      'Katrenikona',
      'Kothapeta',
      'Malikipuram',
      'Mamidikuduru',
      'Mandapeta',
      'Mummidivaram',
      'P. Gannavaram',
      'Razole',
      'Ramachandrapuram',
      'Ravulapalem',
      'Rayavaram',
      'Sakhinetipalle',
      'Thallarevu',
      'Uppalaguptam',
    ],
  },
  {
    district: 'Krishna',
    mandals: [
      'Avanigadda',
      'Bantumilli',
      'Bapulapadu',
      'Challapalli',
      'Ghantasala',
      'Gannavaram',
      'Gudivada',
      'Gudlavalleru',
      'Guduru',
      'Kankipadu',
      'Koduru',
      'Kruthivennu',
      'Machilipatnam North',
      'Machilipatnam South',
      'Mopidevi',
      'Movva',
      'Nagayalanka',
      'Nandivada',
      'Pamarru',
      'Pamidimukkala',
      'Pedana',
      'Pedaparupudi',
      'Penamaluru',
      'Thotlavalluru',
      'Unguturu',
      'Vuyyuru',
    ],
  },
  {
    district: 'Kurnool',
    mandals: [
      'Adoni Rural',
      'Adoni Urban',
      'Alur',
      'Aspari',
      'C. Belagal',
      'Chagalamarri',
      'Chippagiri',
      'Devanakonda',
      'Dhone',
      'Gonegandla',
      'Gudur',
      'Halaharvi',
      'Holagunda',
      'Jupadu Bungalow',
      'Kallur',
      'Kodumur',
      'Kosigi',
      'Kowthalam',
      'Krishnagiri',
      'Kurnool Rural',
      'Kurnool Urban',
      'Maddikera East',
      'Mantralayam',
      'Nandavaram',
      'Orvakal',
      'Pattikonda',
      'Pedda kadabur',
      'Tuggali',
      'Veldurthi',
      'Yemmiganur',
    ],
  },
  {
    district: 'Markapuram',
    mandals: [
      'Ardhaveedu',
      'Bestavaripeta',
      'Chandrasekharapuram',
      'Cumbum',
      'Dornala',
      'Giddalur',
      'Hanumanthunipadu',
      'Kanigiri',
      'Komarolu',
      'Konakanamitla',
      'Markapuram',
      'Pamur',
      'Pedacherlopalle',
      'Pedda Araveedu',
      'Podili',
      'Pullalacheruvu',
      'Racherla',
      'Tarlupadu',
      'Tripuranthakam',
      'Veligandla',
      'Yerragondapalem',
    ],
  },
  {
    district: 'Nandyal',
    mandals: [
      'Allagadda',
      'Atmakur',
      'Banaganapalle',
      'Bandi Atmakur',
      'Bethamcherla',
      'Chagalamarri',
      'Dhone',
      'Dornipadu',
      'Gadivemula',
      'Gospadu',
      'Jupadu Bunglow',
      'Kallur',
      'Kothapalle',
      'Koilkuntla',
      'Kolimigundla',
      'Mahanandi',
      'Miduthuru',
      'Nandikotkur',
      'Nandyal Rural',
      'Nandyal Urban',
      'Owk',
      'Pagidyala',
      'Pamulapadu',
      'Panyam',
      'Peapully',
      'Rudravaram',
      'Sanjamala',
      'Sirivella',
      'Srisailam',
      'Uyyalawada',
      'Velugodu',
    ],
  },
  {
    district: 'NTR',
    mandals: [
      'A.Konduru',
      'Chandarlapadu',
      'G.Konduru',
      'Gampalagudem',
      'Ibrahimpatnam',
      'Jaggayyapeta',
      'Kanchikacherla',
      'Mylavaram',
      'Nandigama',
      'Penuganchiprolu',
      'Reddigudem',
      'Tiruvuru',
      'Vatsavai',
      'Veerullapadu',
      'Vijayawada Central',
      'Vijayawada East',
      'Vijayawada North',
      'Vijayawada Rural',
      'Vijayawada West',
      'Vissannapeta',
    ],
  },
  {
    district: 'Palnadu',
    mandals: [
      'Amaravathi',
      'Atchampet',
      'Bellamkonda',
      'Bollapalle',
      'Chilakaluripeta',
      'Dachepalle',
      'Durgi',
      'Edlapadu',
      'Gurazala',
      'Ipur',
      'Kakumanu',
      'Karempudi',
      'Krosuru',
      'Machavaram',
      'Macherla',
      'Muppalla',
      'Nadendla',
      'Narasaraopet',
      'Nekarikallu',
      'Nuzendla',
      'Pedakurapadu',
      'Piduguralla',
      'Rajupalem',
      'Rentachintala',
      'Rompicherla',
      'Savalyapuram',
      'Sattenapalli',
      'Veldurthi',
      'Vinukonda',
    ],
  },
  {
    district: 'Parvathipuram Manyam',
    mandals: [
      'Balijipeta',
      'Bhamini',
      'Garugubilli',
      'Gajapathinagaram',
      'Gantyada',
      'Gummalaxmipuram',
      'Jiyyammavalasa',
      'Komarada',
      'Kurupam',
      'Makkuva',
      'Palakonda',
      'Panchipenta',
      'Parvathipuram',
      'Peddabayalu',
      'Salur',
      'Seethampeta',
      'Seethanagaram',
      'Veeraghattam',
    ],
  },
  {
    district: 'Polavaram',
    mandals: [
      'Addateegala',
      'Chinturu',
      'Devipatnam',
      'Etapaka',
      'Gangavaram',
      'Gurthedu',
      'Kunavaram',
      'Maredumilli',
      'Rajavommangi',
      'Rampachodavaram',
      'Vara Ramachandrapuram',
      'Y. Ramavaram',
    ],
  },
  {
    district: 'Prakasam',
    mandals: [
      'Addanki',
      'Ardhaveedu',
      'Ballikurava',
      'Chimakurthy',
      'Chirala',
      'Darsi',
      'Donakonda Kanigiri',
      'Giddalur',
      'Gudluru',
      'Hanumanthunipadu',
      'Inkollu',
      'J.Panguluru',
      'Jarugumilli',
      'Kandukuru',
      'Kanigiri',
      'Karamchedu',
      'Kondapi',
      'Korisapadu',
      'Kothapatnam',
      'Kurichedu',
      'Lingasamudram',
      'Maddipadu',
      'Markapur',
      'Martur',
      'Marripudi',
      'Mundlamuru Ongole',
      'Naguluppalapadu',
      'Ongole Rural',
      'Ongole Urban',
      'Pamur',
      'Parchur',
      'Pedacherlopalle',
      'Peddaraveedu',
      'Ponnaluru',
      'Pullalacheruvu',
      'Racherla',
      'Santhamaguluru',
      'Santhanuthalapadu',
      'Singarayakonda',
      'Tarlupadu',
      'Tanguturu',
      'Thallur',
      'Tripuranthakam',
      'Ulavapadu',
      'Veligandla',
      'Vetapalem',
      'Voletivaripalem',
      'Yerragondapalem',
      'Zarugumalli',
    ],
  },
  {
    district: 'Srikakulam',
    mandals: [
      'Amadalavalasa',
      'Bhamini',
      'Burja',
      'Etcherla',
      'Ganguvarisigadam',
      'Gara',
      'Hiramandalam',
      'Ichchapuram',
      'Jalumuru',
      'Kanchili',
      'Kaviti',
      'Kotabommali',
      'Kothuru',
      'Lakshminarasupeta',
      'Laveru',
      'Mandasa',
      'Meliaputti',
      'Nandigama',
      'Narasannapeta',
      'Palakonda',
      'Palasa',
      'Pathapatnam',
      'Polaki',
      'Ponduru',
      'Ranastalam',
      'Regidi Amadalavalasa',
      'Sanaba',
      'Santha Bommali',
      'Saravakota',
      'Sompeta',
      'Srikakulam',
      'Tekkali',
      'Vajrapukotturu',
      'Veeraghattam',
    ],
  },
  {
    district: 'Sri Sathya Sai',
    mandals: [
      'Agali',
      'Amadagur',
      'Amarapuram',
      'Bathalapalle',
      'Bukkapatnam',
      'Chennekothapalle',
      'Chilamathur',
      'Dharmavaram',
      'Gandlapenta',
      'Gorantla',
      'Gudibanda',
      'Hindupur',
      'Kadiri',
      'Kanaganapalle',
      'Kothacheruvu',
      'Lepakshi',
      'Madakasira',
      'Mudigubba',
      'Nallacheruvu',
      'Nallamada',
      'Nambulapulakunta',
      'Obuladevaracheruvu',
      'Parigi',
      'Penukonda',
      'Puttaparthi',
      'Ramagiri',
      'Roddam',
      'Rolla',
      'Somandepalle',
      'Talupula',
      'Tanakal',
      'Tadimarri',
      'Vidapanakal',
      'Yellanur',
    ],
  },
  {
    district: 'Tirupati',
    mandals: [
      'B.Kothakota',
      'Balayapalli',
      'Buchinaidu Kandriga',
      'Chandragiri',
      'Chinnagottigallu',
      'Chitvel',
      'Dakkili',
      'Doravarisatram',
      'Gangavaram',
      'Gudipala',
      'Gurramkonda',
      'Irala',
      'K.V.B.Puram',
      'Kalakada',
      'Kalikiri',
      'Kuppam',
      'Nagalapuram',
      'Nagari',
      'Naidupeta',
      'Narayanavanam',
      'Obulavaripalle',
      'Ozili',
      'Pakala',
      'Palamaner',
      'Peddapanjani',
      'Penagalur',
      'Pellakur',
      'Pichatur',
      'Pileru',
      'Pullampeta',
      'Punganur',
      'Puttur',
      'Railway Koduru',
      'Ramachandrapuram',
      'Ramakuppam',
      'Renigunta',
      'Rompicherla',
      'Santhipuram',
      'Satyavedu',
      'Srikalahasti',
      'Sullurpeta',
      'Tada',
      'Thamballapalle',
      'Thottambedu',
      'Tirupati Rural',
      'Tirupati Urban',
      'Vadamalapeta',
      'Vakadu',
      'Varadaiahpalem',
      'Venkatagiri',
      'Yerpedu',
      'Yerravaripalem',
    ],
  },
  {
    district: 'Visakhapatnam',
    mandals: [
      'Anandapuram',
      'Bheemunipatnam',
      'Gajuwaka',
      'Gopalapatnam',
      'Maharanipeta',
      'Mulagada',
      'Padmanabham',
      'Pedagantyada',
      'Pendurthi',
      'Seethammadhara',
      'Visakhapatnam Rural',
    ],
  },
  {
    district: 'Vizianagaram',
    mandals: [
      'Badangi',
      'Bhogapuram',
      'Bobbili',
      'Bondapalli',
      'Cheepurupalli',
      'Denkada',
      'Dattirajeru',
      'Gajapathinagaram',
      'Garividi',
      'Gantyada',
      'Gurla',
      'Jami',
      'Kothavalasa',
      'Lakkavarapukota',
      'Merakamudidam',
      'Mentada',
      'Nellimarla',
      'Poosapatirega',
      'Rajam',
      'Ramabhadrapuram',
      'Regidi Amadalavalasa',
      'Santhakavati mandal',
      'Srungavarapukota',
      'Therlam',
      'Vangara',
      'Vepada',
      'Vizianagaram Rural',
      'Vizianagaram Urban',
    ],
  },
  {
    district: 'West Godavari',
    mandals: [
      'Achanta',
      'Akiveedu',
      'Attili',
      'Bhimadole',
      'Bhimavaram',
      'Buttayagudem',
      'Chintalapudi',
      'Denduluru',
      'Dwaraka Tirumala',
      'Eluru',
      'Ganapavaram',
      'Iragavaram',
      'Jangareddygudem',
      'Kalla',
      'Kamavarapukota',
      'Kovvur',
      'Lingapalem',
      'Mogalthur',
      'Nallajerla',
      'Narasapuram',
      'Nidamarru',
      'Palakoderu',
      'Palakollu',
      'Pedapadu',
      'Pedavegi',
      'Penugonda',
      'Penumantra',
      'Pentapadu',
      'Poduru',
      'Polavaram',
      'Tadepalligudem',
      'Tanuku',
      'Thallapudi',
      'Undi',
      'Unguturu',
      'Veeravasaram',
      'Yelamanchili',
    ],
  },
  {
    district: 'Nellore',
    mandals: [
      'Allur',
      'Ananthasagaram',
      'Anumasamudrampeta',
      'Atmakur',
      'Bogole',
      'Buchireddypalem',
      'Chejerla',
      'Chillakur',
      'Dagadarthi',
      'Duttalur',
      'Gudur',
      'Indukurpet',
      'Jaladanki',
      'Kaligiri',
      'Kaluvoya',
      'Kavali',
      'Kodavalur',
      'Kota',
      'Kovur',
      'Manubolu',
      'Marripadu',
      'Muthukur',
      'Nellore Rural',
      'Nellore Urban',
      'Podalakur',
      'Rapur',
      'Sangam',
      'Seetharamapuram',
      'Sydapuram',
      'Thotapalli Gudur',
      'Udayagiri',
      'Venkatachalam',
      'Vidavalur',
      'Vinjamur',
    ],
  },
  {
    district: 'YSR Kadapa',
    mandals: [
      'Atlur',
      'B. Kodur',
      'Badvel',
      'Bramhamgari Matham',
      'Chapadu',
      'Chakarayapet',
      'Chennur',
      'Chinthakommadinne',
      'Duvvur',
      'Gopavaram',
      'Jammalamadugu',
      'Kalasapadu',
      'Kadapa',
      'Kamalapuram',
      'Khajipeta',
      'Kondapuram',
      'Lingala',
      'Muddanur',
      'Mylavaram',
      'Mydukur',
      'Nandalur',
      'Peddamudium',
      'Pendlimarri',
      'Porumamilla',
      'Proddatur',
      'Pulivendula',
      'Rajampeta',
      'Rajupalem',
      'Rayachoti',
      'Siddavatam',
      'Simhadripuram',
      'Sri Avadhutha Kasinayana',
      'T. Sundupalle',
      'Thondur',
      'Vallur',
      'Veeraballi',
      'Veerapunayunipalle',
      'Vempalle',
      'Vemula',
      'Vontimitta',
      'Yerraguntla',
    ],
  },
];

// Get all districts as a simple array
export const getAllDistricts = (): string[] => {
  return andhraPradeshDistricts.map((d) => d.district).sort();
};

// Get mandals for a specific district
export const getMandalsByDistrict = (district: string): string[] => {
  const districtData = andhraPradeshDistricts.find(
    (d) => d.district.toLowerCase() === district.toLowerCase()
  );
  return districtData ? districtData.mandals.sort() : [];
};

// Get all unique mandals across all districts
export const getAllMandals = (): string[] => {
  const allMandals = new Set<string>();
  andhraPradeshDistricts.forEach((district) => {
    district.mandals.forEach((mandal) => allMandals.add(mandal));
  });
  return Array.from(allMandals).sort();
};
