'use client';

import { useState, useEffect } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { visitorAPI } from '@/lib/api';
import { showToast } from '@/lib/toast';
import {
    User, Phone, IdCard, CheckCircle, RefreshCw, Loader2,
    History, Clock, CheckCircle2, AlertCircle, MapPin,
    Users, Info, ChevronRight, Search
} from 'lucide-react';
import { format } from 'date-fns';

export default function VisitorsPage() {
    const [code, setCode] = useState('');
    const [loading, setLoading] = useState(false);
    const [visitorData, setVisitorData] = useState<any>(null);
    const [consuming, setConsuming] = useState(false);
    const [recentVisits, setRecentVisits] = useState<any[]>([]);
    const [loadingRecent, setLoadingRecent] = useState(true);

    const fetchRecentVisits = async () => {
        try {
            const response = await visitorAPI.getRecent();
            if (response.success) {
                setRecentVisits(response.data);
            }
        } catch (error) {
            console.error('Error fetching recent visits:', error);
        } finally {
            setLoadingRecent(false);
        }
    };

    useEffect(() => {
        fetchRecentVisits();
    }, []);

    const handleVerify = async (e?: React.FormEvent) => {
        if (e) e.preventDefault();
        if (!code || code.length !== 6) {
            showToast.error('Please enter a valid 6-digit code');
            return;
        }

        setLoading(true);
        setVisitorData(null);
        try {
            const response = await visitorAPI.verifyCode(code);
            if (response.success) {
                setVisitorData(response.data);
                showToast.success('Code verified successfully');
            } else {
                showToast.error(response.message || 'Invalid or expired code');
            }
        } catch (error: any) {
            showToast.error(error.response?.data?.message || 'Verification failed');
        } finally {
            setLoading(false);
        }
    };

    const handleConsume = async () => {
        if (!visitorData) return;

        setConsuming(true);
        try {
            const response = await visitorAPI.consumeCode(code, visitorData.lead_id);
            if (response.success) {
                showToast.success('Attendance confirmed successfully!');
                setVisitorData(null);
                setCode('');
                fetchRecentVisits();
            } else {
                showToast.error(response.message || 'Failed to confirm attendance');
            }
        } catch (error: any) {
            showToast.error(error.response?.data?.message || 'Action failed');
        } finally {
            setConsuming(false);
        }
    };

    return (
        <div className="min-h-screen bg-slate-50/50 dark:bg-slate-950/20 py-8 px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto">
                {/* Header Section */}
                <div className="mb-10 flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-slate-200 dark:border-slate-800 pb-8">
                    <div>
                        <div className="flex items-center gap-2 mb-3">
                            <div className="px-3 py-1 bg-orange-100 dark:bg-orange-900/30 text-orange-600 dark:text-orange-400 text-xs font-black uppercase tracking-tighter rounded-full border border-orange-200 dark:border-orange-800">
                                Admin Portal
                            </div>
                            <div className="px-3 py-1 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 text-xs font-black uppercase tracking-tighter rounded-full border border-indigo-200 dark:border-indigo-800">
                                Visitor Services
                            </div>
                        </div>
                        <h1 className="text-4xl font-black text-slate-900 dark:text-white tracking-tight leading-none">
                            Visitor <span className="text-orange-500 underline decoration-indigo-500/30 text-5xl">Verification</span>
                        </h1>
                        <p className="mt-4 text-slate-500 dark:text-slate-400 max-w-xl font-medium">
                            Verify 6-digit access codes generated by the counseling team and process on-campus attendance for prospective students.
                        </p>
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="text-right hidden sm:block">
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest leading-none mb-1">System Status</p>
                            <p className="text-sm font-bold text-emerald-500 flex items-center justify-end gap-1.5 leading-none">
                                <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                                Live & Synchronized
                            </p>
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                    {/* Left Side: Verification & Data */}
                    <div className="lg:col-span-12 xl:col-span-8 space-y-8">
                        <Card className="p-1 border-none shadow-2xl bg-white dark:bg-slate-900 rounded-[2.5rem] overflow-hidden">
                            <div className="p-8">
                                <div className="flex items-center justify-between mb-8">
                                    <h2 className="text-xl font-black text-slate-800 dark:text-slate-100 flex items-center gap-3 italic">
                                        <div className="w-10 h-10 rounded-2xl bg-indigo-600 flex items-center justify-center text-white shadow-lg shadow-indigo-500/20">
                                            <Search className="w-5 h-5" />
                                        </div>
                                        Validate Access Code
                                    </h2>
                                    <div className="flex items-center gap-1.5 text-xs font-bold text-slate-400 italic">
                                        <Clock className="w-4 h-4" />
                                        24h Validity Windows
                                    </div>
                                </div>

                                <form onSubmit={handleVerify} className="relative group">
                                    <div className="flex flex-col sm:flex-row gap-4">
                                        <div className="flex-1 relative">
                                            <div className="absolute inset-y-0 left-6 flex items-center pointer-events-none text-slate-300 group-focus-within:text-orange-500 transition-colors">
                                                <IdCard className="w-8 h-8" />
                                            </div>
                                            <input
                                                type="text"
                                                maxLength={6}
                                                placeholder="0 0 0 0 0 0"
                                                value={code}
                                                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                                                className="w-full pl-18 pr-8 py-6 text-3xl tracking-[0.4em] font-black rounded-[2rem] border-4 border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-950 focus:border-orange-500/50 focus:ring-8 focus:ring-orange-500/5 outline-none transition-all placeholder:text-slate-200 dark:placeholder:text-slate-800 shadow-inner text-center sm:text-left"
                                            />
                                        </div>
                                        <Button
                                            type="submit"
                                            disabled={loading || code.length !== 6}
                                            className="sm:w-48 h-[88px] text-xl font-black bg-slate-900 dark:bg-orange-500 hover:bg-orange-600 text-white shadow-2xl shadow-orange-500/20 dark:shadow-none active:scale-95 transition-all rounded-[2rem] flex items-center justify-center gap-3"
                                        >
                                            {loading ? <RefreshCw className="w-6 h-6 animate-spin" /> : 'Verify Now'}
                                        </Button>
                                    </div>
                                </form>
                                <div className="mt-4 flex items-center gap-2 px-2">
                                    <AlertCircle className="w-4 h-4 text-orange-500" />
                                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Only active 6-digit codes generated within the last 24 hours are valid</p>
                                </div>
                            </div>
                        </Card>

                        {visitorData && (
                            <div className="animate-in fade-in slide-in-from-bottom-12 duration-700">
                                <Card className="border-none shadow-[0_32px_64px_-12px_rgba(0,0,0,0.1)] bg-white dark:bg-slate-900 rounded-[2.5rem] overflow-hidden">
                                    {/* Visitor Profile Header */}
                                    <div className="bg-gradient-to-br from-indigo-900 via-indigo-800 to-indigo-950 p-10 text-white relative">
                                        <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -mt-20 -mr-20 blur-3xl opacity-50" />
                                        <div className="absolute bottom-0 left-0 w-48 h-48 bg-orange-500/10 rounded-full -mb-10 -ml-10 blur-2xl" />

                                        <div className="relative flex flex-col md:flex-row md:items-center justify-between gap-8">
                                            <div className="flex items-center gap-6">
                                                <div className="w-24 h-24 rounded-3xl bg-white/10 backdrop-blur-xl flex items-center justify-center text-4xl font-black border border-white/20 shadow-2xl overflow-hidden group">
                                                    <div className="absolute inset-0 bg-gradient-to-tr from-orange-500/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                                                    <span className="relative z-10">{visitorData.lead_name?.charAt(0)}</span>
                                                </div>
                                                <div>
                                                    <div className="flex items-center gap-3 mb-2">
                                                        <span className="px-3 py-1 rounded-full bg-orange-500 text-[10px] font-black uppercase tracking-widest shadow-lg shadow-orange-500/20">
                                                            {visitorData.current_lead_status}
                                                        </span>
                                                        <span className="text-white/40 text-sm font-bold tracking-tight">ENQUIRY #{visitorData.lead_enquiry_number}</span>
                                                    </div>
                                                    <h2 className="text-4xl font-black tracking-tight leading-tight">{visitorData.lead_name}</h2>
                                                    <p className="text-indigo-300/80 text-sm font-bold flex items-center gap-1.5 mt-1">
                                                        <User className="w-4 h-4" />
                                                        Student Profile Validated
                                                    </p>
                                                </div>
                                            </div>

                                            <div className="flex flex-col items-end">
                                                <div className="text-right p-4 rounded-2xl bg-white/5 backdrop-blur-md border border-white/10">
                                                    <p className="text-indigo-300 text-[10px] font-black uppercase tracking-widest mb-1 leading-none">Assigned Telecaller</p>
                                                    <p className="text-xl font-black text-white leading-none">{visitorData.sender_name}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Detailed Information Grid */}
                                    <div className="p-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                                        {/* Contact Card */}
                                        <div className="space-y-3">
                                            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1 italic">Contact Registry</p>
                                            <div className="p-5 rounded-3xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800 group transition-all duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-xl dark:hover:bg-slate-800">
                                                <div className="flex items-center gap-4">
                                                    <div className="w-12 h-12 rounded-2xl bg-indigo-100 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400 group-hover:bg-indigo-600 group-hover:text-white transition-all shadow-sm">
                                                        <Phone className="w-6 h-6" />
                                                    </div>
                                                    <div>
                                                        <p className="text-xs text-slate-500 font-bold mb-0.5">Mobile Registry</p>
                                                        <p className="text-lg font-black text-slate-900 dark:text-slate-100">{visitorData.lead_phone}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Father Information Card */}
                                        <div className="space-y-3">
                                            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1 italic">Parental Ledger</p>
                                            <div className="p-5 rounded-3xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800 group transition-all duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-xl dark:hover:bg-slate-800">
                                                <div className="flex items-center gap-4">
                                                    <div className="w-12 h-12 rounded-2xl bg-orange-100 dark:bg-orange-900/30 flex items-center justify-center text-orange-600 dark:text-orange-400 group-hover:bg-orange-500 group-hover:text-white transition-all shadow-sm">
                                                        <Users className="w-6 h-6" />
                                                    </div>
                                                    <div>
                                                        <p className="text-xs text-slate-500 font-bold mb-0.5">Father's Full Name</p>
                                                        <p className="text-lg font-black text-slate-900 dark:text-slate-100 truncate max-w-[150px]">
                                                            {visitorData.lead_father_name || 'Not Recorded'}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Geography Card */}
                                        <div className="space-y-3">
                                            <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1 italic">Origin Mapping</p>
                                            <div className="p-5 rounded-3xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800 group transition-all duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-xl dark:hover:bg-slate-800">
                                                <div className="flex items-center gap-4">
                                                    <div className="w-12 h-12 rounded-2xl bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center text-emerald-600 dark:text-emerald-400 group-hover:bg-emerald-500 group-hover:text-white transition-all shadow-sm">
                                                        <MapPin className="w-6 h-6" />
                                                    </div>
                                                    <div>
                                                        <p className="text-xs text-slate-500 font-bold mb-0.5">District Area</p>
                                                        <p className="text-lg font-black text-slate-900 dark:text-slate-100 truncate max-w-[150px]">
                                                            {visitorData.lead_district || 'N/A Location'}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Detailed Geography Footer */}
                                    <div className="px-10 pb-10 grid grid-cols-1 lg:grid-cols-2 gap-8">
                                        <div className="p-6 rounded-3xl bg-indigo-50/50 dark:bg-indigo-900/10 border border-indigo-100/50 dark:border-indigo-900/20 relative group">
                                            <div className="absolute top-4 right-4 text-indigo-200 dark:text-indigo-900 group-hover:text-indigo-400 transition-colors">
                                                <Info className="w-8 h-8 opacity-20" />
                                            </div>
                                            <h4 className="text-[10px] font-black uppercase tracking-widest text-indigo-500 mb-5 flex items-center gap-2 italic">
                                                <MapPin className="w-3.5 h-3.5" />
                                                Detailed Location Intelligence
                                            </h4>
                                            <div className="grid grid-cols-2 gap-6 relative z-10">
                                                <div className="space-y-1">
                                                    <p className="text-[10px] font-bold text-slate-500 dark:text-slate-500 uppercase tracking-tighter">Mandal/Tahsil</p>
                                                    <p className="text-base font-black text-slate-800 dark:text-slate-200">{visitorData.lead_mandal || '—'}</p>
                                                </div>
                                                <div className="space-y-1">
                                                    <p className="text-[10px] font-bold text-slate-500 dark:text-slate-500 uppercase tracking-tighter">Village/Locality</p>
                                                    <p className="text-base font-black text-slate-800 dark:text-slate-200">{visitorData.lead_village || '—'}</p>
                                                </div>
                                            </div>
                                        </div>

                                        <div className="flex flex-col justify-end">
                                            <Button
                                                onClick={handleConsume}
                                                disabled={consuming}
                                                className="w-full h-20 bg-emerald-600 hover:bg-emerald-700 text-white rounded-[1.5rem] font-black text-2xl shadow-2xl shadow-emerald-500/20 active:scale-95 transition-all flex items-center justify-center gap-4 group"
                                            >
                                                {consuming ? (
                                                    <Loader2 className="w-8 h-8 animate-spin" />
                                                ) : (
                                                    <>
                                                        <CheckCircle2 className="w-8 h-8 transition-transform group-hover:scale-110" />
                                                        Mark Guest Attendance
                                                        <ChevronRight className="w-6 h-6 opacity-40 ml-2 group-hover:translate-x-1 transition-transform" />
                                                    </>
                                                )}
                                            </Button>
                                            <div className="flex items-center justify-center gap-2 mt-4 px-4 py-2 bg-slate-100 dark:bg-slate-800 rounded-xl w-fit mx-auto">
                                                <Clock className="w-3 h-3 text-slate-400" />
                                                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none">
                                                    Expires {format(new Date(visitorData.expires_at), 'PPPp')}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </Card>
                            </div>
                        )}
                    </div>

                    {/* Right Side: Activity Log */}
                    <div className="lg:col-span-12 xl:col-span-4 h-full">
                        <Card className="border-none shadow-2xl bg-white dark:bg-slate-900 rounded-[2.5rem] h-full flex flex-col overflow-hidden max-h-[85vh] sticky top-8">
                            <div className="p-8 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50/30 dark:bg-slate-800/20">
                                <div>
                                    <h3 className="font-black text-2xl text-slate-900 dark:text-white flex items-center gap-3 tracking-tighter">
                                        Recent <span className="text-indigo-600">Requests</span>
                                    </h3>
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mt-1">Real-time Verification Feed</p>
                                </div>
                                <button
                                    onClick={fetchRecentVisits}
                                    className="p-4 bg-white dark:bg-slate-800 shadow-md border border-slate-100 dark:border-slate-700 hover:bg-orange-500 hover:text-white rounded-2xl transition-all active:scale-90 group"
                                    title="Manual Re-sync"
                                >
                                    <RefreshCw className={`w-5 h-5 ${loadingRecent ? 'animate-spin' : 'group-hover:rotate-180 transition-transform duration-500'}`} />
                                </button>
                            </div>

                            <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
                                {loadingRecent ? (
                                    <div className="flex flex-col items-center justify-center py-20 gap-4 opacity-50">
                                        <div className="relative">
                                            <Loader2 className="w-12 h-12 animate-spin text-orange-500" />
                                            <div className="absolute inset-0 flex items-center justify-center">
                                                <div className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse" />
                                            </div>
                                        </div>
                                        <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Polling System Assets...</p>
                                    </div>
                                ) : recentVisits.length === 0 ? (
                                    <div className="text-center py-24 space-y-4 opacity-30 px-10">
                                        <div className="w-20 h-20 mx-auto bg-slate-100 dark:bg-slate-800 rounded-3xl flex items-center justify-center">
                                            <History className="w-10 h-10 text-slate-300" />
                                        </div>
                                        <div>
                                            <p className="text-sm font-black uppercase tracking-tighter">Log Empty</p>
                                            <p className="text-xs font-medium">Waiting for first visitor interaction.</p>
                                        </div>
                                    </div>
                                ) : (
                                    recentVisits.map((visit) => (
                                        <div
                                            key={visit.id}
                                            className={`p-5 rounded-3xl border-2 transition-all duration-300 group cursor-default shadow-sm hover:shadow-md ${visit.status === 'used'
                                                    ? 'bg-emerald-50/40 border-emerald-100/50 dark:bg-emerald-900/10 dark:border-emerald-900/30'
                                                    : visit.status === 'expired'
                                                        ? 'bg-rose-50/40 border-rose-100/50 dark:bg-rose-900/10 dark:border-rose-900/30'
                                                        : 'bg-indigo-50/40 border-indigo-100/50 dark:bg-indigo-900/10 dark:border-indigo-900/30'
                                                }`}
                                        >
                                            <div className="flex items-center gap-4 mb-4">
                                                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center text-sm font-black shadow-lg transition-transform group-hover:scale-110 ${visit.status === 'used'
                                                        ? 'bg-emerald-600 text-white shadow-emerald-500/20'
                                                        : visit.status === 'expired'
                                                            ? 'bg-rose-600 text-white shadow-rose-500/20'
                                                            : 'bg-indigo-600 text-white shadow-indigo-500/20'
                                                    }`}>
                                                    {visit.status === 'used' ? <CheckCircle2 className="w-6 h-6" /> : visit.code}
                                                </div>
                                                <div className="flex-1 min-w-0">
                                                    <div className="flex items-center justify-between gap-2 overflow-hidden">
                                                        <h4 className="font-black text-slate-900 dark:text-slate-100 truncate group-hover:text-indigo-600 transition-colors uppercase tracking-tight leading-none text-base">
                                                            {visit.lead_name}
                                                        </h4>
                                                        <span className={`px-2 py-0.5 rounded-lg text-[9px] font-black uppercase tracking-widest ${visit.status === 'used'
                                                                ? 'bg-emerald-200 text-emerald-800'
                                                                : visit.status === 'expired'
                                                                    ? 'bg-rose-200 text-rose-800'
                                                                    : 'bg-indigo-200 text-indigo-800'
                                                            }`}>
                                                            {visit.status}
                                                        </span>
                                                    </div>
                                                    <div className="flex items-center gap-1.5 mt-2">
                                                        <div className="w-1.5 h-1.5 rounded-full bg-slate-300 group-hover:bg-orange-500 transition-colors" />
                                                        <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest truncate">From: {visit.sender_name}</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="flex items-center justify-between pl-1 pt-3 border-t border-slate-200/50 dark:border-slate-700/50">
                                                <div className="flex items-center gap-1.5 text-slate-400 group-hover:text-slate-600 transition-colors">
                                                    <Clock className="w-3.5 h-3.5" />
                                                    <span className="text-[10px] font-black uppercase tracking-widest leading-none">
                                                        {format(new Date(visit.created_at), 'MMM d, h:mm a')}
                                                    </span>
                                                </div>
                                                <div className="text-[10px] font-black text-indigo-600 bg-indigo-50 dark:bg-slate-950 px-2.5 py-1 rounded-xl border border-indigo-100/50 dark:border-indigo-900/40">
                                                    #{visit.lead_enquiry_number}
                                                </div>
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>

                            <div className="p-6 bg-slate-50 dark:bg-slate-800 shadow-inner text-center border-t border-slate-100 dark:border-slate-800">
                                <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] italic">System Master Log • Top 10 Records</p>
                            </div>
                        </Card>
                    </div>
                </div>
            </div>
        </div>
    );
}
